name = "PyPlotTools"
uuid = "9ae3cb79-3f6f-4998-aea7-8967ca7d6c02"
authors = ["Felix Horger <felix.horger@kcl.ac.uk>"]
version = "0.1.0"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
